<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net8.0\InventoryLearning.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net8.0\InventoryLearning.GlobalUsings.g.cs" />
    <Compile Include="obj\Debug\net8.0\InventoryLearning.MvcApplicationPartsAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="obj\Debug\net8.0\ApiEndpoints.json" />
    <Content Include="obj\Debug\net8.0\EndpointInfo\InventoryLearning.json" />
    <Content Include="obj\Debug\net8.0\InventoryLearning.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net8.0\rjsmcshtml.dswa.cache.json" />
    <Content Include="obj\Debug\net8.0\rjsmrazor.dswa.cache.json" />
    <Content Include="obj\Debug\net8.0\rpswa.dswa.cache.json" />
    <Content Include="obj\Debug\net8.0\staticwebassets.build.endpoints.json" />
    <Content Include="obj\Debug\net8.0\staticwebassets.build.json" />
    <Content Include="obj\Debug\net8.0\staticwebassets.references.upToDateCheck.txt" />
    <Content Include="obj\Debug\net8.0\staticwebassets.removed.txt" />
    <Content Include="obj\InventoryLearning.csproj.nuget.dgspec.json" />
    <Content Include="obj\project.assets.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.29">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="obj\Debug\net8.0\staticwebassets\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="obj\Debug\net8.0\apphost.exe" />
    <None Include="obj\Debug\net8.0\EndpointInfo\InventoryLearning.OpenApiFiles.cache" />
    <None Include="obj\Debug\net8.0\Inventor.F5385425.Up2Date" />
    <None Include="obj\Debug\net8.0\InventoryLearning.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net8.0\InventoryLearning.assets.cache" />
    <None Include="obj\Debug\net8.0\InventoryLearning.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net8.0\InventoryLearning.csproj.BuildWithSkipAnalyzers" />
    <None Include="obj\Debug\net8.0\InventoryLearning.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net8.0\InventoryLearning.dll" />
    <None Include="obj\Debug\net8.0\InventoryLearning.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net8.0\InventoryLearning.genruntimeconfig.cache" />
    <None Include="obj\Debug\net8.0\InventoryLearning.MvcApplicationPartsAssemblyInfo.cache" />
    <None Include="obj\Debug\net8.0\InventoryLearning.pdb" />
    <None Include="obj\Debug\net8.0\refint\InventoryLearning.dll" />
    <None Include="obj\Debug\net8.0\ref\InventoryLearning.dll" />
    <None Include="obj\Debug\net8.0\staticwebassets.build.json.cache" />
    <None Include="obj\InventoryLearning.csproj.nuget.g.props" />
    <None Include="obj\InventoryLearning.csproj.nuget.g.targets" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>

</Project>
